### ISSUE TITLE
Could anyone deploy the latest update in the library?

### ISSUE THREAD

**Issue by jinbeeahn** [d6u/react-container-query#137]
Yesterday a PR got merged to master but that latest fix hasn't been published yet.

Could any contributors or author publish it please?
(the latest change is basically adding react 18 to peerDependencies in package.json)

**Comment by d6u** [comment]
Sorry about the delay. Just bumped version to v0.13 https://github.com/react-container-query/react-container-query/commit/c7b607098a8fa9e7a13e4d6d1bdc73fc0249e686 and publish to NPM https://www.npmjs.com/package/react-container-query.
