### ISSUE TITLE
Use with stateless functional components throws a TypeError

### ISSUE THREAD

**Issue by pabloen** [d6u/react-container-query#15]
Trying to use this library with a stateless functional component throws the following error:

`Uncaught TypeError: Cannot read property 'clientWidth' of null`

**Comment by d6u** [comment]
@pabloen Yeah, this is a known limitation with stateless function components. When we pass `ref` property to a function component, the `ref` is not called with the root element of the function component. At this point, you have to use the class component.

**Comment by moimael** [comment]
The recommended way to fix it is to wrap the wrapped stateless component into an intermediate HOC from which you get the ref in the applyContainerQuery HOC. See here for more info : https://github.com/facebook/react/issues/4936

**Comment by d6u** [comment]
This is no longer an issue since the high order component API is complete removed, see [0.7 release](https://github.com/d6u/react-container-query/releases/tag/v0.7.0).
