### ISSUE TITLE
Option to choose between box model

### ISSUE THREAD

**Issue by moimael** [d6u/react-container-query#16]
Hi,

I started using your project for our company website rewrite, and so far I really appreciate it.
One issue I face though is that I need to choose how react-container-query calculate width of component when setting property.

My issue is the following:

I have a container component with content and a left + right padding passed as props (lets say it's 230px for the example). I want the padding to be removed when container size is below 400px. It obviously wont work because with the padding, the container size will always be at least 460px. So allowing to choose how the lib calculate width (including/excuding margin/padding) would help.

Thanks !

**Comment by d6u** [comment]
Thanks! This is a good feature. But to be honest this is not on top of my list now. I'm more interested in finding a way to improve performance. So this implementation is likely to delay. But you are welcome to create a PR, I will happen to work with you to merge it.

**Comment by moimael** [comment]
Ok I'll have a look for a PR, in the meantime, do you think of any workaround I could use ? Thanks :)

**Comment by d6u** [comment]
@moimael you could put react-container-query component as a child of the component with padding. So this way it will react to the width without including the padding.

**Comment by d6u** [comment]
This should also be fixed. From [0.5.0 release](https://github.com/d6u/react-container-query/releases/tag/v0.5.0), I'm using `window.getComputedStyle` to get width and height, so whatever box model apply the container element should be reflected when getting width and height. Let me know how this works.
