### ISSUE TITLE
Do not throw error when returning null component.

### ISSUE THREAD

**Issue by moimael** [d6u/react-container-query#20]
Hi,

Right now, if I pass a component which can return null to react container query, I get an error saying it can not get clientWidth of null. Since returning null component is perfectly valid in React, could this case be catched in the library ?

A workaround for now is to return <noscript />.

Thanks !

**Comment by d6u** [comment]
Thanks for reporting. I'm in the middle of refactoring this library to be more performant. Once that's done, I will address this issue ASAP!

**Comment by moimael** [comment]
Thanks for your quick answer :) Do you have any ETA for the refactoring ?

**Comment by d6u** [comment]
Hi, please check out [0.5.0 release](https://github.com/d6u/react-container-query/releases/tag/v0.5.0)! This should be fixed. You can reopen this if it still doesn't work.
