### ISSUE TITLE
react-container-query do not include element-resize-detector

### ISSUE THREAD

**Issue by moimael** [d6u/react-container-query#24]
Hi,

Specifying element-resize-detector as a peerDependency would make sense (along with React), or updating the doc at least to indicate you have to install it manually.

EDIT: Actually, even after installing it manually, it still complains : 
`Error: Cannot find module "element-resize-detector"`

Thanks !

**Comment by d6u** [comment]
Sorry for the obvious mistake. I just released 0.5.3 and put element-resize-detector inside dependency instead of devDependency. I tested this, it works on my setup. Let me know if you still have problem.
