### ISSUE TITLE
setAttributes replacement

### ISSUE THREAD

**Issue by moimael** [d6u/react-container-query#25]
Hi,

We rely quite a lot on the setAttributes api to be able to change the css (used with css modules) depending on the size of the container. What is the migration path, now that it is removed ? 

I would really like not doing it in the js via inline styles.

Thanks, keep up the good work :)

**Comment by d6u** [comment]
Thanks for your feedback. In your wrapped component, you need to use `containerQuery` property to specify class names on the root element:

```jsx
import classnames from 'classnames';

...
<div className={classnames('container', this.props.containerQuery)}>
...
```

This way, in you CSS you can just use class name selector instead of attribute selector. Does this work for you?

**Comment by moimael** [comment]
Not really, since I use css modules, classnames are namespaced automatically, and adding a :global keyword on each container query class is not clean.

**Comment by d6u** [comment]
I see, what about using something like this? This way you can not only use CSS module, but hash query names as well.

```js
import css from 'css.css';

class MyComponent extends Component {
  render() {
    return (
      <div className={classnames('container', this.props.containerQuery)}>
        <div className='box'>the box</div>
      </div>
    );
  }
}

const query = {
  // Define queries using ES6 enhanced object literals computed (dynamic) property names
  [css['width-between-400-and-599']]: {
    minWidth: 400,
    maxWidth: 599
  },
  [css['width-larger-than-600']]: {
    minWidth: 600,
  }
};

const HigherOrderComponent = applyContainerQuery(MyComponent, query);
```

Let me know if this works for you.

**Comment by moimael** [comment]
It seems to work nicely :) I am in the process of converting everything, I'll let you know if I hit any issues.

**Comment by d6u** [comment]
Closing, seems like this is resolved.
