### ISSUE TITLE
element-resize-detector throw a bunch of warnings

### ISSUE THREAD

**Issue by moimael** [d6u/react-container-query#26]
It seems that element-resize-detector throws a bunch of warning when used in react-container-query.

I see a lot of those :
`current only pixel value height and width are supported, "auto" is not a pixel value`

or

`current only pixel value height and width are supported, "100%" is not a pixel value`

Any idea why ?

Thanks !

**Comment by d6u** [comment]
Can you show me which browser is this happening, what the basic structure of that component and what's the CSS and inline style apply to the root element of the component?

**Comment by moimael** [comment]
For the browser it's happening on Latest Firefox release, haven't tried any other browsers yet. I'll try to provide you with more info but I need to extract it first, it's quite a big project.

**Comment by d6u** [comment]
The warning was coded inside one of the helper functions https://github.com/d6u/react-container-query/blob/cd79b15f01ef03995ae58dfa1fb0f1a0f81cac7a/src/utils.ts#L23 because I was worried get arbitrary values when getting widths. However, I couldn't reproduce the that in FireFox. Love to  fix this if you have reproducible example. Thanks!

**Comment by moimael** [comment]
Thanks for the follow up ! I'm on a very tight deadline right now, hence my lack on answer, but I'll try to update our project and reproduce it for you !

**Comment by moimael** [comment]
I do not understand how to consistently reproduce this, I'm not sure why it throws the error in the first place.

**Comment by d6u** [comment]
It doesn't throw the error so everything will still work. It just [logs it](https://github.com/d6u/react-container-query/blob/959d06ee21e52481fbe2d631a27abee65c2534b3/src/utils.ts#L23) when it runs into things it didn't know how to parse.

I've tested this in FF and Chrome, it seems like "display: none" will log `"auto" is not a pixel value`, but I haven't seem `"100%" is not a pixel value`. I need some time to confirm as I'm occupied right now. But I can at least remove the `console.log` in production.

**Comment by moimael** [comment]
Yes you're right. Thanks for investigating ! Removing console.log in production would definitely help :)

**Comment by d6u** [comment]
I have released 0.5.5, please check it out. I will leave this open since we haven't figured the root issue yet.

**Comment by d6u** [comment]
This is solved in [0.7](https://github.com/d6u/react-container-query/releases/tag/v0.7.0) by treating values other than pixel as 0. This is aligned with the fact that when "auto" is detected for an element, the element will be `display: blank`.
