### ISSUE TITLE
Make react-container-query work with es7 decorators

### ISSUE THREAD

**Issue by moimael** [d6u/react-container-query#29]
It would be awesome to be able to use this lib as an es7 decorator.

Right now I get an error when I try to use it : 

``` javascript
      if (this.__reactAutoBindPairs.length) {
              ^

TypeError: Cannot read property '__reactAutoBindPairs' of undefined
```

**Comment by d6u** [comment]
Thanks for the recommendation. However, I don't think I will implement this before decorator spec becomes official. See [Babel decorator doc](http://babeljs.io/docs/plugins/transform-decorators/).

**Comment by elado** [comment]
I created a helper:

```js
import { applyContainerQuery } from 'react-container-query'

const containerQuery = queries => component => applyContainerQuery(component, queries)

// ...

@containerQuery({
  xyz: {
    maxWidth: 900
  }
})
export default class Blah extends Component {
   ...
}
```

**Comment by d6u** [comment]
Thanks, guys. Decorator pattern no longer works here since the high order component API is complete removed, see [0.7 release](https://github.com/d6u/react-container-query/releases/tag/v0.7.0).
