### ISSUE TITLE
Doesn't work when wrapping stateless components

### ISSUE THREAD

**Issue by colbycheeze** [d6u/react-container-query#30]
Here is the code:

```
import React from 'react';
import { applyContainerQuery } from 'react-container-query';

class TestQuery extends React.Component {
  render() {
    return (
      <p>
        <h5>Class Container</h5>
        {this.props.containerQuery.big ? 'big' : 'small'}
      </p>
    );
  }
}

const TestStateless = (props) => (
  <p>
     <h5>Stateless Container</h5>
    {props.containerQuery.big ? 'big' : 'small'}
  </p>
);

const query = {
  big: {
    minWidth: 600,
  },
};

const TestQueryWrapper = applyContainerQuery(TestQuery, query);
const TestStatelessWrapper = applyContainerQuery(TestStateless, query);

export const Query = () => (
  <div>
    <TestQueryWrapper />
    <TestStatelessWrapper />
  </div>
);

export default Query;
```

![image](https://cloud.githubusercontent.com/assets/8884298/17674891/18a95f7e-62ed-11e6-840c-4c26cf809cc3.png)

it seems to be passing an empty object
![image](https://cloud.githubusercontent.com/assets/8884298/17674977/60484cdc-62ed-11e6-8a6b-6cfb15eb121f.png)

**Comment by d6u** [comment]
Related to #15

**Comment by rdjpalmer** [comment]
@d6u should be able to close this now, no? Same for #15.

**Comment by d6u** [comment]
Thanks, guys. This is no longer an issue since the high order component API is complete removed, see [0.7 release](https://github.com/d6u/react-container-query/releases/tag/v0.7.0).
