### ISSUE TITLE
Modularize functions for outside libraries

### ISSUE THREAD

**Issue by souporserious** [d6u/react-container-query#31]
Hey, how do you feel about pulling `toPairs`, and `parseQuery` functions out into their own library? Sometimes I have to go with the traditional DOM and wanted to create a similar "container query" plugin for when I don't have access to React. This is a very rough example http://codepen.io/souporserious/pen/01bae977653e5b0e1230bb95e6eb162d?editors=0010 that uses the same functions to achieve almost the same API in a traditional DOM environment.

**Comment by d6u** [comment]
This should be a good idea. Do you have any thought on the public API? I guess the package just have to expose `parseQuery`. Does the current signature fit your need?

**Comment by d6u** [comment]
Also, what do you think it should be named. `parse-query` is already used.

**Comment by souporserious** [comment]
Yeah that signature fits my need 👍  Hmm `resolve-query`? I'll try and think of some more.

**Comment by souporserious** [comment]
Any update on this? Would you like me to create the library and this one can point to it?

**Comment by d6u** [comment]
Hey @souporserious, thanks for your patient. I just created https://github.com/d6u/container-query-toolkit this morning. `parseQuery` is available as a standalone package (it's called `matchQueries` now).

Just to be future looking, do you think to create a Github organization will facilitate the development collaboration here? I have some plan written down here https://github.com/d6u/react-container-query/projects/1. But it might be hard for myself to work on this timely. Let me know what you think.

**Comment by d6u** [comment]
I'm closing as the issue itself is resolved.

**Comment by souporserious** [comment]
Thank you! That was quick 😱  I love the idea of having a Github organization. I think anything that we can keep away from a framework will help get more outsiders to help.

**Comment by rdjpalmer** [comment]
+1 on the organisation. Seems like a good way to push further development. Would be good to flesh out the plan with which bits you think would be best to pull out, improve etc.

**Comment by d6u** [comment]
I have written a draft for the first next step here --> https://github.com/d6u/react-container-query/issues/39. I plan to introduce a completely new API, so please take a look and let me know what do you think.
