### ISSUE TITLE
`containerQuery` prop should be removed by `applyContainerQuery`

### ISSUE THREAD

**Issue by silasb** [d6u/react-container-query#32]
I feel that `applyContainerQuery` should remove the `containerQuery` propType from it's wrapped component.

The wrapped component returned by `applyContainerQuery` will also have the `isRequired` prop defined, but it doesn't make sense since it will never receive that property from it's owner.

**Comment by silasb** [comment]
Actually on second thought we shouldn't even be hoisting the `propTypes` to the WrappedComponent.

I think we can remove this line: https://github.com/d6u/react-container-query/blob/master/src/applyContainerQuery.ts#L12

None of the other popular libraries hoist them.  react-redux and react-intl come to mind.

The component still gets mounted and React will still call on the propTypes of the WrappedComponent for validation.

**Comment by d6u** [comment]
> I feel that applyContainerQuery should remove the containerQuery propType from it's wrapped component.

I don't quite understand this. I don't think we ever specified a propType for `containerQuery` property. Can you point me to the specific code?

**Comment by d6u** [comment]
> Actually on second thought we shouldn't even be hoisting the propTypes of the WrappedComponent.

This change was from https://github.com/d6u/react-container-query/pull/11. I don't use propType myself. Maybe @psachs21 can help here?

**Comment by silasb** [comment]
The composite component will pull in the props of the WrappedComponent on [this line](https://github.com/d6u/react-container-query/blob/master/src/applyContainerQuery.ts#L12).  If the WrappedComponents defines 

```
propTypes = {
containerQuery: React.....
}
```

then the composite component will also include that props, which it shouldn't.  The idea with HOCs is that we shouldn't hoist the props to the composite container.

**Comment by d6u** [comment]
I see now, that make a lot of sense. I will remove it shortly. Thanks for explaining that to me.

**Comment by d6u** [comment]
This should be fixed, see https://github.com/d6u/react-container-query/releases/tag/v0.5.6
