### ISSUE TITLE
Use different resize strategy

### ISSUE THREAD

**Issue by FezVrasta** [d6u/react-container-query#33]
I have developed a small React component that detects the resize of elements using the `<object>` resize event. It's similar to what you are using right now but it's more reliable and needs just an additional element instead of the current ~7 elements with all the DOM manipulation and so on.  
Also, it doesn't manipulate the DOM directly, being written with React.

Maybe it could be a good candidate to improve this library?

https://github.com/fezvrasta/react-resize-aware

**Comment by d6u** [comment]
Hey, I haven't checked out your code, but that sounds amazing. I will test out its cross-browser compatibility once I have time (maybe within a week). Feel free to create a PR if you cannot wait 😄

**Comment by FezVrasta** [comment]
Unfortunately I've not a lot of free time, I just wanted to give my contribution to this project because it's something much needed on the Front-End development field.

If you need help with the integration just leave me a message anywhere you like (on my github page are described few ways) and I'll try to help 🙃

**Comment by d6u** [comment]
I checked out the underlying library I used to get resize event (element-resize-detector) and found out it already [supports object strategy](https://github.com/wnr/element-resize-detector/blob/751dacaa6be8d58ca214030a67b94395e08e7eea/src/detection-strategy/object.js). I don't know which one is better, "object" or "scroll" strategy. Can you briefly explain the advantages of "object" strategy besides its cleaner when you have time? It also has some [benchmark](https://github.com/wnr/element-resize-detector/tree/751dacaa6be8d58ca214030a67b94395e08e7eea/benchmark), I will run them when I have time.

**Comment by FezVrasta** [comment]
I think the biggest advantage is the number of DOM elements needed to make the method work. Also, the scroll strategy needs a lot of CSS which can break if the page has some weird CSS applied to it. With object you just use a native triggered event with the purpose of notify resize events, not scroll events.

**Comment by souporserious** [comment]
element-resize-detector has the ability to do both https://github.com/wnr/element-resize-detector#create-instance the object strategy is deprecated though, I'm guessing because scroll based is more performant? Not sure what you mean about number of DOM elements @FezVrasta ? It only adds one additional element https://github.com/wnr/element-resize-detector#caveats

**Comment by FezVrasta** [comment]
If you look at the source code, it's being added one element with inside it several other elements.

**Comment by d6u** [comment]
I'm going to close this since currently I'd prefer to use a more performant strategy from element-resize-detector. Thanks for the information!
