### ISSUE TITLE
Getting empty object. Sometimes.

### ISSUE THREAD

**Issue by silasb** [d6u/react-container-query#37]
I'm using react-redux.

I'm getting an weird issue.  My component has `applyContainerQuery` being applied to it, but I have a redux container wrapping it. Looks like this:

```
<Connect(MyComponent)>
  <ContainerQuery(MyComponent)>
     <MyComponent>
  </ContainerQuery(MyContainer)>
</Connect(MyComponent)>
```

When I reload the page my component console logs out `this.props.containerQuery` and it results in an empty object.

Has anyone seen this with react-redux?

The only time that I can get it to not give me an empty object is when the HMR reloads the code.  If I manually reload the page I'll always get an empty object.  Really stumping me.

UPDATE: I figured it out.  One of my developers added in an at the top of the `render()` function:

```
if (!item.id) {
   return null;
}
```

**Comment by d6u** [comment]
@silasb Thanks for the update!
