### ISSUE TITLE
New Component Style API (work with stateless component and ResizeObserver API)

### ISSUE THREAD

**Issue by d6u** [d6u/react-container-query#39]
## The Need to Design API for the Future

The new [ResizeObserver API](https://developers.google.com/web/updates/2016/10/resizeobserver) provides a native browser API to listen to element resize event. For unsupported browsers, to listen to resize event, we use [element-resize-detector](https://github.com/wnr/element-resize-detector), which requires inserting sentinel elements to the DOM. E.g.

``` html
<div class="box" style="position: relative">
  <div class="content"> ... </div>
  <div class="sentinel"> ... </div>
</div>
```

In the above markup, `.box` is our component. `.sentinel` is inserted for observing resize event. A `style="position: relative"` is also added to `.box` for `.sentinel` to work. It's possible that those added styles and elements can mess up with the component styles.

However, if ResizeObserver API made into production, the markup can be reduced to:

``` html
<div class="box">
  <div class="content"> ... </div>
</div>
```

In order to be future looking and transition to ResizeObserver API without developer changing their code, we have to design react-container-query API around the usage of ResizeObserver.
## Limitation of Current API

The current API uses a higher order component pattern:

``` js
const HigherOrderComponent = applyContainerQuery(BoxComponent, {
  'width-between-400-and-599': {
    minWidth: 400,
    maxWidth: 599
  }
});
```

This API is limited because it cannot apply container query to stateless components (see [Issue #15](https://github.com/d6u/react-container-query/issues/15)). A workaround is to wrap BoxComponent with another element (see [PR #38](https://github.com/d6u/react-container-query/pull/38)). So the markup will become:

``` html
<div class="container" style="position: relative">
  <div class="box">
    <div class="content"> ... </div>
  </div>
  <div class="sentinel"> ... </div>
</div>
```

`.container` is a newly added element to wrap BoxComponent. It has several downsides:
- `.container` is redundant if ResizeObserver is available.
- It changes the intended HTML structure. If we expect BoxComponent to be responsive, we don't expect another element to wrap it.

The `applyContainerQuery` API also has some limitations. When to design the BoxComponent, the responsive logic is handled by passing a property from outside. BoxComponent doesn't know the outside logics but it is required to work with the logic. This is not strictly modular code.
## New API Design

To make the API easier to reason and be future looking. I propose to create a new component style API:

``` jsx
import ContainerQuery from 'react-container-query';

// Same query structure as before
const query = { ... };

const Box = () => (
  <ContainerQuery query={query} tagName="div" className="box">
    {(matchedQueries) => (
      <div className="content"> ... </div>
    )}
  </ContainerQuery>
);
```

Here we pass a function as the child of `ContainerQuery`. The function will only be called when `matchedQueries` changes. It has several advantages:
- Work with stateless component naturally while maintaining compatibility with future ResizeObserver API.
- Component composing code stays closer to view code. Easier to reason about.

**Comment by d6u** [comment]
# react-container-query to utilize ResizeObserver

## The Need to Design API for the Future

The new [ResizeObserver API](https://developers.google.com/web/updates/2016/10/resizeobserver) provides a native browser API to listen to element resize event. For unsupported browsers, to listen to resize event, we use [element-resize-detector](https://github.com/wnr/element-resize-detector), which requires inserting sentinel elements to the DOM. E.g.

```html
<div class="box" style="position: relative">
  <div class="content"> ... </div>
  <div class="sentinel"> ... </div>
</div>
```

In the above markup, `.box` is our component. `.sentinel` is inserted for observing resize event. A `style="position: relative"` is also added to `.box` for `.sentinel` to work. It's possible that those added styles and elements can mess up with the component styles.

However, if ResizeObserver API made into production, the markup can be reduced to:

```html
<div class="box">
  <div class="content"> ... </div>
</div>
```

In order to be future looking and transition to ResizeObserver API without developer changing their code, we have to design react-container-query API around the usage of ResizeObserver.

## Limitation of Current API

The current API uses a higher order component pattern:

```js
const HigherOrderComponent = applyContainerQuery(BoxComponent, {
  'width-between-400-and-599': {
    minWidth: 400,
    maxWidth: 599
  }
});
```

This API is limited because it cannot apply container query to stateless components (see [Issue #15](https://github.com/d6u/react-container-query/issues/15)). A workaround is to wrap BoxComponent with another element (see [PR #38](https://github.com/d6u/react-container-query/pull/38)). So the markup will become:

```html
<div class="container" style="position: relative">
  <div class="box">
    <div class="content"> ... </div>
  </div>
  <div class="sentinel"> ... </div>
</div>
```

`.container` is a newly added element to wrap BoxComponent. It has several downsides:

- `.container` is redundant if ResizeObserver is available.
- It changes the intended HTML structure. If we expect BoxComponent to be responsive, we don't expect another element to wrap it.

The `applyContainerQuery` API also has some limitations. When to design the BoxComponent, the responsive logic is handled by passing a property from outside. BoxComponent doesn't know the outside logics but it is required to work with the logic. This is not strictly modular code.

## New API Design

To make the API easier to reason and be future looking. I propose to create a new component style API:

```jsx
import ContainerQuery from 'react-container-query';

// Same query structure as before
const query = { ... };

const Box = () => (
  <ContainerQuery query={query} tagName="div" className="box">
    {(matchedQueries) => (
      <div className="content"> ... </div>
    )}
  </ContainerQuery>
);
```

Here we pass a function as the child of `ContainerQuery`. The function will only be called when `matchedQueries` changes. It has several advantages:

- Work with stateless component naturally while maintaining compatibility with future ResizeObserver API.
- Component composing code stays closer to view code. Easier to reason about.

**Comment by d6u** [comment]
I plan to work on this new API this week if there is new ideas.

**Comment by d6u** [comment]
An example that uses the API can be found here https://github.com/d6u/react-container-query/blob/e1427ee433bedd2a31dd8b4b8961ae4ab9449335/examples/toggle-sizes/index.js#L40-L48 and there https://github.com/d6u/react-container-query/blob/e1427ee433bedd2a31dd8b4b8961ae4ab9449335/examples/simple/index.js#L16-L20.

**Comment by d6u** [comment]
Progress please see https://github.com/d6u/react-container-query/pull/40

**Comment by d6u** [comment]
This is implemented in [0.7 release](https://github.com/d6u/react-container-query/releases/tag/v0.7.0).

**Comment by elado** [comment]
Not sure I understand why there's a need of another element (`<div>`) here. Can you please re-explain?

If it's because of the `ref`, and you need a DOM reference of the element, why not using `ReactDOM.findDOMNode(this)`, and just rendering `this.props.children`? Calling that from a parent component will get the dom element of the first component that actually renders DOM.
Maybe I got it wrong though.

**Comment by d6u** [comment]
Thanks @elado! `ReactDOM.findDOMNode(this)` is exactly what I needed. I hope I know this before. Does that mean this way, I don't have to wrap `children` with one additional `<div>` parent? Is there any caveat to pay attention to?

**Comment by elado** [comment]
Yay. Correct, you need something like:

```jsx
class ContainerQueryWrapper extends Component {
  componentDidMount() {
    // ...
    // this will get the first DOM element from whatever the children renders.
    const domEl = ReactDOM.findDOMNode(this)
    this.rol.observe(domEl)
  }

  render() {
    return React.Children.only(this.props.children)
  }
}
```

**Comment by elado** [comment]
And you can still keep the HOC/decorator with that.

**Comment by d6u** [comment]
Hi @elado, thanks for your advise, now 0.8 supports both HOC and Component style API without wrapping element thanks to `ReactDOM.findDOMNode(this)`.
