### ISSUE TITLE
Expose wrapped component propTypes

### ISSUE THREAD

**Issue by moimael** [d6u/react-container-query#41]
Hi,

It would be very useful (for example with react storybook) to expose the wrapped component propTypes on the applyContainerQuery HOC.

Something like that :

``` javascript
ContainerQuery.propTypes = {
  <containerquery proptypes>,
  ...WrappedComponent.propTypes,
}
```

**Comment by d6u** [comment]
Hi, thanks for the suggestion. I'm currently working on a brand new API that will, hopefully, once for all resolve all issues in this repo, please take a look --> https://github.com/d6u/react-container-query/issues/39. I also believe it will help resolve your issue as well.

**Comment by d6u** [comment]
This is no longer a issue since the high order component API is complete removed, see [0.7 release](https://github.com/d6u/react-container-query/releases/tag/v0.7.0).
