### ISSUE TITLE
Shouldn't you save this to `dependencies` instead of `devDependencies`?

### ISSUE THREAD

**Issue by ha404** [d6u/react-container-query#42]

**Comment by d6u** [comment]
By `this` you are referring to? Could you provide a little more context?

**Comment by hawsome** [comment]
Sorry, I meant the installation instructions: `npm i -D react-container-query`.

Should this be `npm i -S react-container-query` instead?

**Comment by d6u** [comment]
@ha404 Thanks for your concern, this is mostly your call. This package is not opinionated :)

**Comment by ha404** [comment]
Hmm, I guess my question would be in what scenarios would I only want this sort of package in dev dependencies? Thanks @d6u!

**Comment by d6u** [comment]
Got it! Yeah either way it should work :)
