### ISSUE TITLE
Use resize observer polyfill

### ISSUE THREAD

**Issue by souporserious** [d6u/react-container-query#45]
Hey 👋 thought I would let you know, I updated React Measure to use [this new-ish polyfill](https://github.com/que-etc/resize-observer-polyfill) and it has been working great so far. Figured your library could benefit so I wanted to share with you in case you were interested 🙂

**Comment by d6u** [comment]
@souporserious thanks. This is cool. ResizeObserver has been on my list for a while as while. Thanks for sharing. FYI, I've been using [this little module](https://github.com/d6u/resize-observer-lite) I abstracted to "polyfill" ResizeObserver with element-resize-detector.
