### ISSUE TITLE
Props not passed from parent container

### ISSUE THREAD

**Issue by elado** [d6u/react-container-query#48]
https://github.com/d6u/react-container-query/blob/master/src/index.tsx#L69

```js
return <Component containerQuery={this.state.params}/>;
```

should be

```js
return <Component containerQuery={this.state.params} {...this.props} />;
```

**Comment by d6u** [comment]
Thanks for reporting. Love to fix this but caught a cold. PR is welcome. Otherwise you might have to wait a bit.

Also I prefer to put ...props in front of state.xxx this way props with the same name won't overwrite it.

**Comment by d6u** [comment]
Thanks for reporting. Fixed. See https://github.com/d6u/react-container-query/blob/19ce687f2c010476a6de731841d8ebe06680c974/src/index.tsx#L86
