### ISSUE TITLE
Interested by this project but not with mixins

### ISSUE THREAD

**Issue by slorber** [d6u/react-container-query#5]
Hi,

I'm interested in using this project, as I planned to build something very similar myself (and did not even know a spec was ongoing for CSS for this problem).

I don't like some details of the implementation, particularly the usage of mixins and the impossibility to easily use this with inline styling or change the component layout entirely on breakpoint reached.

I would rather use an API that use [HOC](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750) and looks like:

```javascript
class MyComponent extends Component {
  render() {
    const className = cx("container",{small: this.props.small, big: this.props.big});
    return (
      <div className={className}>
        <div className='box'>the box</div>
      </div>
    );
  }
}


module.exports = ReactContainerQuery.injectQueryResult(MyComponent,{
  small: {
    minWidth: 400,
    maxWidth: 599
  },
  big: {
    minWidth: 600,
  }
});
```

I like the idea of having full control of the mediaquery result in plain JS and not using mixins.

**Comment by d6u** [comment]
Hi @slorber,

Thanks for your feedback. I don't remember exactly what was the obstacle of implementing a HOC solution when I begin. But I tried HOC approach this morning and I think it should work. I will work on that in the next few days.

About API using `props` you still can achieve the same thing now. You need to implement a [lifecycle hook](https://github.com/d6u/react-container-query#lifecycle) and set `stateMap` to `this.state`. But yes, if I can implement HOC, you should be able to just use `this.props`.

**Comment by d6u** [comment]
Hi @slorber, I have added HOC API and updated the [doc](https://github.com/d6u/react-container-query#applycontainerquerycomponent-query-opts). Let me know how that works for you.

**Comment by slorber** [comment]
thanks will try to see how it fits in my project when i have time to work on this
