### ISSUE TITLE
Error when unmounting component

### ISSUE THREAD

**Issue by gbentaieb** [d6u/react-container-query#50]
When the component provided to applyContainerQuery is unmounting and resized before being completely unmounted, I have the following error:

Uncaught TypeError: Cannot read property 'onShrink' of undefined

I work on a web video player, and when my player is unmounted, it exits fullscreen, hence the problem. Apparently, it might be due to a wrong implementation of element-resize-detector. See: https://github.com/wnr/element-resize-detector/issues/54

Thanks for your help.

**Comment by d6u** [comment]
Thanks for reporting this. Could you show me a sample code code that can reproduce your error? Also that's the versions of dependencies you are using, e.g. React version?

**Comment by gbentaieb** [comment]
Well, after updating the package to its latest version on npm, I no longer can reproduce the error. My bad, I should have done that before posting an issue. Sorry, and thanks for the support ! :)

**Comment by d6u** [comment]
No problem. Thanks for clarify!
