### ISSUE TITLE
Make it into a Babel plugin

### ISSUE THREAD

**Issue by gajus** [d6u/react-container-query#57]
See as an example https://www.npmjs.com/package/jsx-control-statements

This would make the callback syntax redundant.

**Comment by d6u** [comment]
Thanks for the recommendation. Not sure how to approach this though. I'm also pretty neutral on Babel. No matter who will do this, it should be a separate package.

**Comment by d6u** [comment]
I will close this since I don't have time work on this, if anyone is interested please reopen.
