### ISSUE TITLE
Having issues integrating with Rebass

### ISSUE THREAD

**Issue by loganpowell** [d6u/react-container-query#62]
I'm having an issue trying to integrate this into an app using the [Rebass]() library. I thought I was off to a good start thanks to [this comment](https://github.com/styled-components/styled-components/issues/416#issuecomment-276230181), but I'm still not getting the two libraries to work together...

Here's my code, which doesn't hide the text when the width is within the query threshold:

```js
import React from 'react';
import { NavLink, Text } from 'rebass'
import styled from 'styled-components'
import {ContainerQuery} from 'react-container-query';
import classnames from 'classnames';
import Icon from '../icon'

const query = {
  'small': {
    minWidth: 200,
    maxWidth: 599
  }
};

const ResponsiveText = styled(Text)`
  .small {
    display: none;
  }
`

const NavItem = ({className, children, icon, ml}) => {
  return(
    <NavLink ml={ml}>
      <Icon name={icon}/>
      <ContainerQuery query={query}>
        {(params) => (
          <ResponsiveText children={children} className={classnames(params, `${className}`)} />
        )}
      </ContainerQuery>
    </NavLink>
  )
}

export default NavItem
```
I also found this from mxstbr: https://github.com/callemall/material-ui/issues/6115#issuecomment-279142783

Any pointers?

**Comment by d6u** [comment]
Interesting, I have used no Rebass and very little styled-component. But before I can find some time to try this out myself, it seems a little odd to do:

```
const ResponsiveText = styled(Text)`
  .small {
    display: none;
  }
`
```

Instead of

```
const ResponsiveText = styled(Text)`
  display: none;
`
```

Maybe you mean?

```
const ResponsiveText = styled(Text)`
  &.small {
    display: none;
  }
`
```

**Comment by loganpowell** [comment]
I'm an idiot, I was setting the breakpoint for the entire header rather than the individual component... old habits die hard! Sorry for bothering you! Thank you for the great work and your patience.

**Comment by d6u** [comment]
👏😄
