### ISSUE TITLE
Large asset size

### ISSUE THREAD

**Issue by swese44** [d6u/react-container-query#66]
Hello. `react-container-query` looks like a great solution but it exports a 42kb minified JS file. It doesn't look like this package itself is very large, do you know which dependencies are responsible for the size, and whether we could trim that down? Thanks!

**Comment by d6u** [comment]
Hi, thanks for the feedback. I see the dependencies are primarily those https://github.com/d6u/react-container-query/blob/e61ce9dd51bd220d259e219a3555f1d96d6eba14/package.json#L31-L33. Where lodash I mainly just used a partial require https://github.com/d6u/react-container-query/blob/master/src/ContainerQueryCore.ts#L1. I think the size can come from different sources. Do you have a way to analyze bundle composition we can get a better idea where the weight is from?

**Comment by ZeeCoder** [comment]
I recommend [size-limit](https://yarnpkg.com/en/package/size-limit) or that webpack size analyising plugin in general.

**Comment by swese44** [comment]
looks like `lodash.isequal`provides an index.js file 1800+ lines long which minifies down to about 14kb, since we're just comparing 2 query objects we could probably do a much cheaper comparison.

taking a quick glance at `resize-observer-lite`'s source it seems to be fairly large, it's probably the bulk of the extra weight but i don't know what we could do about that :/

**Comment by d6u** [comment]
Yeah, resize-observer-lite depends on element-resize-detector, I haven't update that dependency for a long time, maybe they are smaller in newer version. https://github.com/d6u/resize-observer-lite/blob/817b192216c352214a45dc39f72fe895cb2b0964/package.json#L21-L23

I'm looking for help here. Otherwise I will have to find a time when I'm not too busy :P

**Comment by swese44** [comment]
looks like we'd get a firefox iframe bugfix by udpating `element-resize-detector`, but it won't reduce the filesize (18kb minified JS).

it looks like the main optimization will be replacing `lodash.isequal`'s 14kb minified JS with something tiny

**Comment by bkniffler** [comment]
Wouldn't shallowly comparing with something like `fbjs/lib/shallowEqual` (source: https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/core/shallowEqual.js) be perfectly fine? It is used by react PureComponent.

**Comment by d6u** [comment]
Improved by #69, will close this and merge #69 and push new version to NPM once tests passed.

I have completely removed lodash from dependencies, I think the bundle came down to about 22kb. Thanks everyone for helping here! I'm not sure I can further reduce the size, but if you have any idea, PR is welcome.

**Comment by swese44** [comment]
late to reply, but wanted to say thanks for addressing this!!
