### ISSUE TITLE
Question: Might this work with React Native?

### ISSUE THREAD

**Issue by loganpowell** [d6u/react-container-query#67]
Couldn't find anything in docs or issues, but wondering if `react-container-query` works in React Native?

**Comment by d6u** [comment]
Thanks for the interest. Although I don’t think it will. Because it relies
on many DOM APIs.

**Comment by loganpowell** [comment]
@d6u wasn't sure if you might be interested, but if you ever wish to enable React Native, there may be a way via [Dimensions.addEventListener](https://facebook.github.io/react-native/docs/dimensions.html#addeventlistener). 

There's even a helper library:

https://hackernoon.com/responsive-uis-in-react-native-a406b5d6c36a

Love what you are doing here. Just thought you'd like to know!

**Comment by d6u** [comment]
I do have interest to expand to RN, although don't not personally use RN so I'm lacking motivation :P Thanks for the reference!
