### ISSUE TITLE
React 15 - remove peerDependencies

### ISSUE THREAD

**Issue by bkniffler** [d6u/react-container-query#7]
Hey, would you mind removing peerDependencies so we can choose the appropriate react version ourselves? Many libraries turned their backs to peerDependencies now.

**Comment by d6u** [comment]
@bkniffler I basically followed [Redux's package.json](https://github.com/reactjs/react-redux/blob/master/package.json#L98). Do you think it's better if I do `"react": "^0.14.0 || ^15.0.0-rc.1",`?

**Comment by bkniffler** [comment]
That would be okay too! I prefer react-routers way https://github.com/reactjs/react-router/blob/master/package.json of removing the peerDependencies though.

**Comment by d6u** [comment]
@bkniffler Thanks for your recommendation. I opt to remove peer deps. If you have any suggestions to this package, feel free to let me know.

**Comment by d6u** [comment]
@bkniffler You can try this out with v0.4.0

**Comment by NMinhNguyen** [comment]
Hey @d6u it's a little hard for me to tell what React Router's `package.json` looked like on the 17th of March 2016, but if you take a look at the [current version](https://github.com/ReactTraining/react-router/blob/fe16632f2f019d07a704d1be10af033e49c3ed08/packages/react-router/package.json#L35-L37), you'll see it specifies `peerDependencies`, and so do a lot of other React libraries:

* [React Redux](https://github.com/reactjs/react-redux/blob/58b4da690aefcfb341b21d21a5f5248661f7c0b1/package.json#L111-L112)
* [React Virtualized](https://github.com/bvaughn/react-virtualized/blob/0195c825bbcb0150f6b38db01be51a06d7aef557/package.json#L152-L155)
* [Material UI](https://github.com/callemall/material-ui/blob/1067f7b6aef04c8f5854708eade2b6404e3e8d7a/package.json#L58-L61)

**Comment by d6u** [comment]
@NMinhNguyen good point. Maybe I should add them back given there are so many popular examples. Right now I don't see this as a blocker for anyone, so I will wait until I got a chance. But PRs are welcome. Thanks.

**Comment by NMinhNguyen** [comment]
I'll raise a PR later today :) but just to confirm, what versions of React does this library support? Is it okay to assume 14-16?

**Comment by d6u** [comment]
Yes, should work with 14-16. Thanks for working on this!

Best,
Daiwei
