### ISSUE TITLE
Pattern for query props and setting state

### ISSUE THREAD

**Issue by seejamescode** [d6u/react-container-query#74]
I have a card component I apply `react-container-query` to. The card component receives the queries object as a prop and then chooses the most appropriate image url based on image sizes.

I would like to prevent switching to smaller images if the user has already downloaded a larger image. This means I would need to call `setState`, but that is discouraged in the render function.

Is there a pattern for passing a query prop to `ContainerQuery`, but then having it’s change call a setState or component function outside of `render()`?

**Comment by davidspiess** [comment]
I do it like this. 

```jsx
static getDerivedStateFromProps(props, state) {
    const { containerQuery } = props;
    if (!shallowEqual(props.containerQuery, state.containerQuery)) {
      return { containerQuery };
    }
    return null;
}
```
