### ISSUE TITLE
not compatible with libs like react-redux-provide

### ISSUE THREAD

**Issue by SeeThruHead** [d6u/react-container-query#8]
If I try and wrap an element that has already been wrapped by another higher order component it doesn't get the proper ref.

In the very specific case of 'react-redux-provider', the fact that it doesn't hoist the proptypes of the thing it wraps stops react-redux-provide from inspecting the component.

I've got a pr incoming for the first issue.
second issue can be avoided by wrapping after call provide on the component, but it's annoying that the order of wrapping matters, i will look into a fix after.

**Comment by d6u** [comment]
@SeeThruHead This sounds good. Looking forward to see your PR!

BTW, you can always use the [mixin API](https://github.com/d6u/react-container-query#createcontainerquerymixinquery-opts) to avoid the issue of layered higher order components.

**Comment by SeeThruHead** [comment]
Yeah we don't allow any mixins in our codebase anymore.
The change I'm proposing makes it so that the HOC passes down a prop, (the function to call on ref={})
and then you can attach it to whatever react-node you want.

**Comment by d6u** [comment]
@SeeThruHead I see.

Completely unrelated questions, what makes you ban the usage of mixin? I can feel this trend, but is it more like 1. a stylistic choice 2. forward looking (align with ES2105 style) 3. performance or other limitation of mixin?

**Comment by SeeThruHead** [comment]
I personally find it hard to reason about where behaviour comes from.
Also all our react development is with es6 classes or function components. So mixins seem out of place in the codebase.

So I just encountered something odd, upon installing the lib anew and wrapping after provide, the ref is being set correctly! I'm going to investigate more to make sure I haven't screwed anything up but I might not have to modify anything.

**Comment by d6u** [comment]
Cool. Sounds good!

**Comment by d6u** [comment]
I'm closing this for now. Feel free to reopen is still see a problem. Thanks.
